// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package http

import (
	"time"
)

// Defines values for CancelPaymentResponseStatus.
const (
	CancelPaymentResponseStatusCANCELLED CancelPaymentResponseStatus = "CANCELLED"
)

// Valid indicates whether the value is a known member of the CancelPaymentResponseStatus enum.
func (e CancelPaymentResponseStatus) Valid() bool {
	switch e {
	case CancelPaymentResponseStatusCANCELLED:
		return true
	default:
		return false
	}
}

// Defines values for CreatePaymentRequestGatewayType.
const (
	MIDTRANS CreatePaymentRequestGatewayType = "MIDTRANS"
)

// Valid indicates whether the value is a known member of the CreatePaymentRequestGatewayType enum.
func (e CreatePaymentRequestGatewayType) Valid() bool {
	switch e {
	case MIDTRANS:
		return true
	default:
		return false
	}
}

// Defines values for CreatePaymentRequestPaymentMethodType.
const (
	QRIS           CreatePaymentRequestPaymentMethodType = "QRIS"
	VIRTUALACCOUNT CreatePaymentRequestPaymentMethodType = "VIRTUAL_ACCOUNT"
)

// Valid indicates whether the value is a known member of the CreatePaymentRequestPaymentMethodType enum.
func (e CreatePaymentRequestPaymentMethodType) Valid() bool {
	switch e {
	case QRIS:
		return true
	case VIRTUALACCOUNT:
		return true
	default:
		return false
	}
}

// Defines values for CreatePaymentResponseStatus.
const (
	CreatePaymentResponseStatusCANCELLED       CreatePaymentResponseStatus = "CANCELLED"
	CreatePaymentResponseStatusCOMPLETED       CreatePaymentResponseStatus = "COMPLETED"
	CreatePaymentResponseStatusEXPIRED         CreatePaymentResponseStatus = "EXPIRED"
	CreatePaymentResponseStatusFAILED          CreatePaymentResponseStatus = "FAILED"
	CreatePaymentResponseStatusINITIATED       CreatePaymentResponseStatus = "INITIATED"
	CreatePaymentResponseStatusPENDING         CreatePaymentResponseStatus = "PENDING"
	CreatePaymentResponseStatusPROCESSING      CreatePaymentResponseStatus = "PROCESSING"
	CreatePaymentResponseStatusREFUNDED        CreatePaymentResponseStatus = "REFUNDED"
	CreatePaymentResponseStatusREFUNDFAILED    CreatePaymentResponseStatus = "REFUND_FAILED"
	CreatePaymentResponseStatusREFUNDREQUESTED CreatePaymentResponseStatus = "REFUND_REQUESTED"
)

// Valid indicates whether the value is a known member of the CreatePaymentResponseStatus enum.
func (e CreatePaymentResponseStatus) Valid() bool {
	switch e {
	case CreatePaymentResponseStatusCANCELLED:
		return true
	case CreatePaymentResponseStatusCOMPLETED:
		return true
	case CreatePaymentResponseStatusEXPIRED:
		return true
	case CreatePaymentResponseStatusFAILED:
		return true
	case CreatePaymentResponseStatusINITIATED:
		return true
	case CreatePaymentResponseStatusPENDING:
		return true
	case CreatePaymentResponseStatusPROCESSING:
		return true
	case CreatePaymentResponseStatusREFUNDED:
		return true
	case CreatePaymentResponseStatusREFUNDFAILED:
		return true
	case CreatePaymentResponseStatusREFUNDREQUESTED:
		return true
	default:
		return false
	}
}

// Defines values for ErrorResponseCode.
const (
	ALREADYEXISTS       ErrorResponseCode = "ALREADY_EXISTS"
	GATEWAYERROR        ErrorResponseCode = "GATEWAY_ERROR"
	IDEMPOTENCYCONFLICT ErrorResponseCode = "IDEMPOTENCY_CONFLICT"
	INTERNALERROR       ErrorResponseCode = "INTERNAL_ERROR"
	INVALIDINPUT        ErrorResponseCode = "INVALID_INPUT"
	INVALIDSTATE        ErrorResponseCode = "INVALID_STATE"
	NOTFOUND            ErrorResponseCode = "NOT_FOUND"
)

// Valid indicates whether the value is a known member of the ErrorResponseCode enum.
func (e ErrorResponseCode) Valid() bool {
	switch e {
	case ALREADYEXISTS:
		return true
	case GATEWAYERROR:
		return true
	case IDEMPOTENCYCONFLICT:
		return true
	case INTERNALERROR:
		return true
	case INVALIDINPUT:
		return true
	case INVALIDSTATE:
		return true
	case NOTFOUND:
		return true
	default:
		return false
	}
}

// CancelPaymentResponse defines model for CancelPaymentResponse.
type CancelPaymentResponse struct {
	PaymentID string                      `json:"payment_id"`
	Status    CancelPaymentResponseStatus `json:"status"`
}

// CancelPaymentResponseStatus defines model for CancelPaymentResponse.Status.
type CancelPaymentResponseStatus string

// CreatePaymentRequest defines model for CreatePaymentRequest.
type CreatePaymentRequest struct {
	// Amount Amount in the smallest currency unit (e.g. IDR uses no sub-unit, so 15000 = Rp 15.000)
	Amount int64 `json:"amount"`

	// BankCode Required when payment_method_type is VIRTUAL_ACCOUNT (e.g. BCA, BNI, BRI)
	BankCode *string `json:"bank_code,omitempty"`

	// Currency ISO 4217 currency code
	Currency      string `json:"currency"`
	CustomerEmail string `json:"customer_email"`

	// CustomerExternalID Caller-side customer identifier for reconciliation
	CustomerExternalID *string `json:"customer_external_id,omitempty"`
	CustomerName       string  `json:"customer_name"`
	CustomerPhone      *string `json:"customer_phone,omitempty"`
	Description        *string `json:"description,omitempty"`

	// ExpiredAt Desired expiry time; gateway may enforce its own minimum/maximum
	ExpiredAt *time.Time `json:"expired_at,omitempty"`

	// GatewayType Payment gateway to route through
	GatewayType CreatePaymentRequestGatewayType `json:"gateway_type"`

	// Metadata Arbitrary caller-defined key-value pairs passed through to the gateway
	Metadata *map[string]any `json:"metadata,omitempty"`

	// PaymentMethodType Broad payment method category
	PaymentMethodType CreatePaymentRequestPaymentMethodType `json:"payment_method_type"`

	// ReferenceID Caller-assigned stable identifier for this payment (used as idempotency seed)
	ReferenceID string `json:"reference_id"`
}

// CreatePaymentRequestGatewayType Payment gateway to route through
type CreatePaymentRequestGatewayType string

// CreatePaymentRequestPaymentMethodType Broad payment method category
type CreatePaymentRequestPaymentMethodType string

// CreatePaymentResponse defines model for CreatePaymentResponse.
type CreatePaymentResponse struct {
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
	Currency  string    `json:"currency"`

	// PaymentID PayGate-assigned payment identifier
	PaymentID string `json:"payment_id"`

	// PaymentInstructions Gateway-specific fulfilment instructions (e.g. virtual account number, QR code URL)
	PaymentInstructions *map[string]any `json:"payment_instructions,omitempty"`

	// ReferenceID Echo of the caller-supplied reference_id
	ReferenceID string                      `json:"reference_id"`
	Status      CreatePaymentResponseStatus `json:"status"`
}

// CreatePaymentResponseStatus defines model for CreatePaymentResponse.Status.
type CreatePaymentResponseStatus string

// ErrorResponse All error responses share this shape. The `code` field is a machine-readable
// constant that maps to `apperror.Code` on the server.
type ErrorResponse struct {
	Code    ErrorResponseCode `json:"code"`
	Message string            `json:"message"`
}

// ErrorResponseCode defines model for ErrorResponse.Code.
type ErrorResponseCode string

// XServiceName defines model for XServiceName.
type XServiceName = string

// BadRequest All error responses share this shape. The `code` field is a machine-readable
// constant that maps to `apperror.Code` on the server.
type BadRequest = ErrorResponse

// Conflict All error responses share this shape. The `code` field is a machine-readable
// constant that maps to `apperror.Code` on the server.
type Conflict = ErrorResponse

// InternalError All error responses share this shape. The `code` field is a machine-readable
// constant that maps to `apperror.Code` on the server.
type InternalError = ErrorResponse

// NotFound All error responses share this shape. The `code` field is a machine-readable
// constant that maps to `apperror.Code` on the server.
type NotFound = ErrorResponse

// UnprocessableEntity All error responses share this shape. The `code` field is a machine-readable
// constant that maps to `apperror.Code` on the server.
type UnprocessableEntity = ErrorResponse

// CreatePaymentParams defines parameters for CreatePayment.
type CreatePaymentParams struct {
	// XServiceName Identifier of the calling service. Used for idempotency key scoping
	// and audit logging. Must be stable across retries.
	XServiceName XServiceName `json:"X-Service-Name"`
}

// CancelPaymentParams defines parameters for CancelPayment.
type CancelPaymentParams struct {
	// XServiceName Identifier of the calling service. Used for idempotency key scoping
	// and audit logging. Must be stable across retries.
	XServiceName XServiceName `json:"X-Service-Name"`
}

// CreatePaymentJSONRequestBody defines body for CreatePayment for application/json ContentType.
type CreatePaymentJSONRequestBody = CreatePaymentRequest
