// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getOutboxStats = `-- name: GetOutboxStats :many
SELECT
    status,
    COUNT(*)::int AS count,
    COALESCE(EXTRACT(EPOCH FROM (NOW() - MIN(created_at)))::int, 0) AS oldest_age_seconds
FROM outbox_events
WHERE created_at > NOW() - INTERVAL '1 hour'
GROUP BY status
`

type GetOutboxStatsRow struct {
	Status           string
	Count            int32
	OldestAgeSeconds interface{}
}

func (q *Queries) GetOutboxStats(ctx context.Context) ([]GetOutboxStatsRow, error) {
	rows, err := q.db.Query(ctx, getOutboxStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOutboxStatsRow
	for rows.Next() {
		var i GetOutboxStatsRow
		if err := rows.Scan(&i.Status, &i.Count, &i.OldestAgeSeconds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaymentAttemptsByPayment = `-- name: GetPaymentAttemptsByPayment :many
SELECT id, payment_id, gateway_transaction_id, attempt_number, status, error_code, error_message,
       gateway_request, gateway_response, http_status_code, duration_ms, created_at
FROM payment_attempts
WHERE payment_id = $1
ORDER BY attempt_number ASC
`

func (q *Queries) GetPaymentAttemptsByPayment(ctx context.Context, paymentID uuid.UUID) ([]PaymentAttempt, error) {
	rows, err := q.db.Query(ctx, getPaymentAttemptsByPayment, paymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentAttempt
	for rows.Next() {
		var i PaymentAttempt
		if err := rows.Scan(
			&i.ID,
			&i.PaymentID,
			&i.GatewayTransactionID,
			&i.AttemptNumber,
			&i.Status,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.GatewayRequest,
			&i.GatewayResponse,
			&i.HttpStatusCode,
			&i.DurationMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaymentEventsByPayment = `-- name: GetPaymentEventsByPayment :many
SELECT id, aggregate_id, aggregate_type, event_type, sequence_number, payload, created_by, created_at
FROM payment_events
WHERE aggregate_id = $1
ORDER BY sequence_number ASC
`

func (q *Queries) GetPaymentEventsByPayment(ctx context.Context, aggregateID uuid.UUID) ([]PaymentEvent, error) {
	rows, err := q.db.Query(ctx, getPaymentEventsByPayment, aggregateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentEvent
	for rows.Next() {
		var i PaymentEvent
		if err := rows.Scan(
			&i.ID,
			&i.AggregateID,
			&i.AggregateType,
			&i.EventType,
			&i.SequenceNumber,
			&i.Payload,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRefundsByPayment = `-- name: GetRefundsByPayment :many
SELECT id, payment_id, reference_id, gateway_refund_id, status, amount, reason,
       gateway_response_payload, created_at, updated_at, deleted_at
FROM refunds
WHERE payment_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetRefundsByPayment(ctx context.Context, paymentID uuid.UUID) ([]Refund, error) {
	rows, err := q.db.Query(ctx, getRefundsByPayment, paymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Refund
	for rows.Next() {
		var i Refund
		if err := rows.Scan(
			&i.ID,
			&i.PaymentID,
			&i.ReferenceID,
			&i.GatewayRefundID,
			&i.Status,
			&i.Amount,
			&i.Reason,
			&i.GatewayResponsePayload,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
