// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT key, payment_id, http_status, response_body, expires_at
FROM idempotency_keys
WHERE key = $1 AND expires_at > NOW()
`

type GetIdempotencyKeyRow struct {
	Key          string
	PaymentID    uuid.UUID
	HttpStatus   int32
	ResponseBody json.RawMessage
	ExpiresAt    pgtype.Timestamptz
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, key string) (GetIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, key)
	var i GetIdempotencyKeyRow
	err := row.Scan(
		&i.Key,
		&i.PaymentID,
		&i.HttpStatus,
		&i.ResponseBody,
		&i.ExpiresAt,
	)
	return i, err
}

const insertIdempotencyKey = `-- name: InsertIdempotencyKey :exec
INSERT INTO idempotency_keys (key, payment_id, http_status, response_body, expires_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (key) DO NOTHING
`

type InsertIdempotencyKeyParams struct {
	Key          string
	PaymentID    uuid.UUID
	HttpStatus   int32
	ResponseBody json.RawMessage
	ExpiresAt    pgtype.Timestamptz
}

func (q *Queries) InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, insertIdempotencyKey,
		arg.Key,
		arg.PaymentID,
		arg.HttpStatus,
		arg.ResponseBody,
		arg.ExpiresAt,
	)
	return err
}
