// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Payment struct {
	ID                     uuid.UUID
	ReferenceID            string
	CallerService          string
	GatewayType            string
	GatewayTransactionID   *string
	Status                 string
	Amount                 int64
	Currency               string
	PaymentMethodType      *string
	CustomerInfo           json.RawMessage
	Metadata               []byte
	GatewayRequestPayload  []byte
	GatewayResponsePayload []byte
	Description            pgtype.Text
	ExpiredAt              *time.Time
	PaidAt                 *time.Time
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	DeletedAt              *time.Time
}

type PaymentAttempt struct {
	ID                   uuid.UUID
	PaymentID            uuid.UUID
	GatewayTransactionID *string
	AttemptNumber        int32
	Status               string
	ErrorCode            *string
	ErrorMessage         pgtype.Text
	GatewayRequest       []byte
	GatewayResponse      []byte
	HttpStatusCode       pgtype.Int4
	DurationMs           pgtype.Int8
	CreatedAt            pgtype.Timestamptz
}

type PaymentEvent struct {
	ID             uuid.UUID
	AggregateID    uuid.UUID
	AggregateType  string
	EventType      string
	SequenceNumber int32
	Payload        json.RawMessage
	CreatedBy      string
	CreatedAt      pgtype.Timestamptz
}
