// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getPendingOutboxEvents = `-- name: GetPendingOutboxEvents :many
SELECT id, aggregate_id, event_type, payload, retry_count
FROM outbox_events
WHERE status = 'PENDING'
  AND scheduled_at <= NOW()
ORDER BY created_at
LIMIT $1
FOR UPDATE SKIP LOCKED
`

type GetPendingOutboxEventsRow struct {
	ID          uuid.UUID
	AggregateID uuid.UUID
	EventType   string
	Payload     json.RawMessage
	RetryCount  int32
}

func (q *Queries) GetPendingOutboxEvents(ctx context.Context, limit int32) ([]GetPendingOutboxEventsRow, error) {
	rows, err := q.db.Query(ctx, getPendingOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingOutboxEventsRow
	for rows.Next() {
		var i GetPendingOutboxEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.RetryCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO outbox_events (aggregate_id, event_type, payload)
VALUES ($1, $2, $3)
`

type InsertOutboxEventParams struct {
	AggregateID uuid.UUID
	EventType   string
	Payload     json.RawMessage
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent, arg.AggregateID, arg.EventType, arg.Payload)
	return err
}

const markOutboxEventFailed = `-- name: MarkOutboxEventFailed :exec
UPDATE outbox_events
SET status       = CASE WHEN retry_count >= 5 THEN 'FAILED' ELSE 'PENDING' END,
    retry_count  = retry_count + 1,
    last_error   = $2,
    scheduled_at = NOW() + (retry_count * INTERVAL '30 seconds')
WHERE id = $1
`

type MarkOutboxEventFailedParams struct {
	ID        uuid.UUID
	LastError pgtype.Text
}

func (q *Queries) MarkOutboxEventFailed(ctx context.Context, arg MarkOutboxEventFailedParams) error {
	_, err := q.db.Exec(ctx, markOutboxEventFailed, arg.ID, arg.LastError)
	return err
}

const markOutboxEventPublished = `-- name: MarkOutboxEventPublished :exec
UPDATE outbox_events
SET status       = 'PUBLISHED',
    published_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkOutboxEventPublished(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxEventPublished, id)
	return err
}
