// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getExpiredPayments = `-- name: GetExpiredPayments :many
SELECT id, reference_id, caller_service, gateway_type, gateway_transaction_id,
       status, amount, currency, payment_method_type,
       customer_info, metadata, gateway_request_payload, gateway_response_payload,
       description, expired_at, paid_at, created_at, updated_at, deleted_at
FROM payments
WHERE status IN ('PENDING', 'INITIATED')
  AND expired_at < NOW()
  AND deleted_at IS NULL
LIMIT $1
`

func (q *Queries) GetExpiredPayments(ctx context.Context, limit int32) ([]Payment, error) {
	rows, err := q.db.Query(ctx, getExpiredPayments, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.ReferenceID,
			&i.CallerService,
			&i.GatewayType,
			&i.GatewayTransactionID,
			&i.Status,
			&i.Amount,
			&i.Currency,
			&i.PaymentMethodType,
			&i.CustomerInfo,
			&i.Metadata,
			&i.GatewayRequestPayload,
			&i.GatewayResponsePayload,
			&i.Description,
			&i.ExpiredAt,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaymentByGatewayTransactionID = `-- name: GetPaymentByGatewayTransactionID :one
SELECT id, reference_id, caller_service, gateway_type, gateway_transaction_id,
       status, amount, currency, payment_method_type,
       customer_info, metadata, gateway_request_payload, gateway_response_payload,
       description, expired_at, paid_at, created_at, updated_at, deleted_at
FROM payments
WHERE gateway_transaction_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPaymentByGatewayTransactionID(ctx context.Context, gatewayTransactionID *string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByGatewayTransactionID, gatewayTransactionID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.ReferenceID,
		&i.CallerService,
		&i.GatewayType,
		&i.GatewayTransactionID,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethodType,
		&i.CustomerInfo,
		&i.Metadata,
		&i.GatewayRequestPayload,
		&i.GatewayResponsePayload,
		&i.Description,
		&i.ExpiredAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, reference_id, caller_service, gateway_type, gateway_transaction_id,
       status, amount, currency, payment_method_type,
       customer_info, metadata, gateway_request_payload, gateway_response_payload,
       description, expired_at, paid_at, created_at, updated_at, deleted_at
FROM payments
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPaymentByID(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.ReferenceID,
		&i.CallerService,
		&i.GatewayType,
		&i.GatewayTransactionID,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethodType,
		&i.CustomerInfo,
		&i.Metadata,
		&i.GatewayRequestPayload,
		&i.GatewayResponsePayload,
		&i.Description,
		&i.ExpiredAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPaymentByReference = `-- name: GetPaymentByReference :one
SELECT id, reference_id, caller_service, gateway_type, gateway_transaction_id,
       status, amount, currency, payment_method_type,
       customer_info, metadata, gateway_request_payload, gateway_response_payload,
       description, expired_at, paid_at, created_at, updated_at, deleted_at
FROM payments
WHERE reference_id = $1 AND caller_service = $2 AND deleted_at IS NULL
`

type GetPaymentByReferenceParams struct {
	ReferenceID   string
	CallerService string
}

func (q *Queries) GetPaymentByReference(ctx context.Context, arg GetPaymentByReferenceParams) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByReference, arg.ReferenceID, arg.CallerService)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.ReferenceID,
		&i.CallerService,
		&i.GatewayType,
		&i.GatewayTransactionID,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethodType,
		&i.CustomerInfo,
		&i.Metadata,
		&i.GatewayRequestPayload,
		&i.GatewayResponsePayload,
		&i.Description,
		&i.ExpiredAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertPayment = `-- name: InsertPayment :exec
INSERT INTO payments (
    id, reference_id, caller_service, gateway_type, gateway_transaction_id,
    status, amount, currency, payment_method_type,
    customer_info, metadata, gateway_request_payload, gateway_response_payload,
    description, expired_at, paid_at, created_at, updated_at
) VALUES (
    $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18
) ON CONFLICT (reference_id, caller_service) DO NOTHING
`

type InsertPaymentParams struct {
	ID                     uuid.UUID
	ReferenceID            string
	CallerService          string
	GatewayType            string
	GatewayTransactionID   *string
	Status                 string
	Amount                 int64
	Currency               string
	PaymentMethodType      *string
	CustomerInfo           json.RawMessage
	Metadata               []byte
	GatewayRequestPayload  []byte
	GatewayResponsePayload []byte
	Description            pgtype.Text
	ExpiredAt              *time.Time
	PaidAt                 *time.Time
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

func (q *Queries) InsertPayment(ctx context.Context, arg InsertPaymentParams) error {
	_, err := q.db.Exec(ctx, insertPayment,
		arg.ID,
		arg.ReferenceID,
		arg.CallerService,
		arg.GatewayType,
		arg.GatewayTransactionID,
		arg.Status,
		arg.Amount,
		arg.Currency,
		arg.PaymentMethodType,
		arg.CustomerInfo,
		arg.Metadata,
		arg.GatewayRequestPayload,
		arg.GatewayResponsePayload,
		arg.Description,
		arg.ExpiredAt,
		arg.PaidAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :exec
UPDATE payments SET status = $1, updated_at = NOW() WHERE id = $2
`

type UpdatePaymentStatusParams struct {
	Status string
	ID     uuid.UUID
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error {
	_, err := q.db.Exec(ctx, updatePaymentStatus, arg.Status, arg.ID)
	return err
}
