// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment_event.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const insertPaymentEvent = `-- name: InsertPaymentEvent :exec
INSERT INTO payment_events (aggregate_id, aggregate_type, event_type, sequence_number, payload)
VALUES ($1, 'PAYMENT', $2, $3, $4)
`

type InsertPaymentEventParams struct {
	AggregateID    uuid.UUID
	EventType      string
	SequenceNumber int32
	Payload        json.RawMessage
}

func (q *Queries) InsertPaymentEvent(ctx context.Context, arg InsertPaymentEventParams) error {
	_, err := q.db.Exec(ctx, insertPaymentEvent,
		arg.AggregateID,
		arg.EventType,
		arg.SequenceNumber,
		arg.Payload,
	)
	return err
}
